name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change to master if that's your default branch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Swift 6
        run: |
          brew install swift@6  # Ensure Swift 6 is installed
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          swift --version  # Verify Swift 6 is being used

      - name: Build the site
        run: |
          swift run  # Or your specific build command for the site generator

  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Assuming the build output is in the 'Build' folder
          cd Build  # Navigate to your build folder (update path if different)

          git add -A
          git commit -m "Deploy new changes"
          
          # Push to the 'gh-pages' branch (or your target branch)
          git push origin HEAD:gh-pages
