name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change to master if that's your default branch

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      
    - name: Build site
      run: swift run
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Output