name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Swift 6
        run: |
          brew install swiftenv  # Install swiftenv
          swiftenv install 6.0.0  # Install Swift 6.0.0 using swiftenv
          swiftenv global 6.0.0  # Set Swift 6 as the global version
          swift --version  # Verify the installed Swift version

      - name: Install dependencies
        run: |
          swift package resolve  # Resolve and fetch project dependencies

      - name: Build the site using Ignite
        run: |
          ignite build  # Build the static site

      - name: Verify build output
        run: |
          ls -la  # List the files in the current directory
          ls -la output  # Check if 'output' folder exists

  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Navigate to the output folder where the built site is stored
          ls -la  # List all files in the current directory
          ls -la output  # Make sure the 'output' folder exists

          # Navigate to the output folder and push the built site to 'gh-pages' branch
          cd output
          git add -A  # Stage all files for commit
          git commit -m "Deploy new changes"  # Commit the changes
          git push origin HEAD:gh-pages  # Push the changes to the 'gh-pages' branch
